// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.project-portfolio-admin@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const PROJECT_PORTFOLIO_ADMIN_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PROJECT_PORTFOLIO_ADMIN_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_project_portfolio_admin { () => { "{\"capability_id\":\"lenso.project-portfolio-admin@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"archive_initiative\",\"attach_project\",\"detach_project\",\"reorder_projects\",\"update_project_snapshot\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_project_portfolio_admin_client { () => { "{\"capability_id\":\"lenso.project-portfolio-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_project_portfolio_admin_client { () => { "{\"capability_id\":\"lenso.project-portfolio-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const ARCHIVE_INITIATIVE_OPERATION: &str = "archive_initiative";
pub const ATTACH_PROJECT_OPERATION: &str = "attach_project";
pub const DETACH_PROJECT_OPERATION: &str = "detach_project";
pub const REORDER_PROJECTS_OPERATION: &str = "reorder_projects";
pub const UPDATE_PROJECT_SNAPSHOT_OPERATION: &str = "update_project_snapshot";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ArchiveInitiativeRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "initiative_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_id: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ArchiveInitiativeResponse {
    #[serde(rename = "archived")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub archived: bool,
    #[serde(rename = "archived_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub archived_at: Option<Timestamp>,
    #[serde(rename = "initiative_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_id: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ArchiveInitiativeError {
    AlreadyAttached,
    Archived,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    NotAttached,
    NotFound,
    OperationInProgress,
    PositionConflict,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AttachProjectRequest {
    #[serde(rename = "expected_initiative_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_initiative_revision: String,
    #[serde(rename = "health")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub health: Health,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "initiative_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_id: String,
    #[serde(rename = "name_snapshot")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name_snapshot: String,
    #[serde(rename = "observed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_at: Timestamp,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "position")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub position: i64,
    #[serde(rename = "progress")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub progress: i64,
    #[serde(rename = "project_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub project_id: String,
    #[serde(rename = "snapshot_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub snapshot_revision: String,
    #[serde(rename = "status_category")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status_category: Status,
    #[serde(rename = "target_date")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_date: Option<String>,
    #[serde(rename = "target_start")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_start: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum Health {
    #[serde(rename = "on_track")]
    OnTrack,
    #[serde(rename = "at_risk")]
    AtRisk,
    #[serde(rename = "off_track")]
    OffTrack,
    #[serde(rename = "no_update")]
    NoUpdate,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum Status {
    #[serde(rename = "backlog")]
    Backlog,
    #[serde(rename = "planned")]
    Planned,
    #[serde(rename = "started")]
    Started,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "canceled")]
    Canceled,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AttachProjectResponse {
    #[serde(rename = "health")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub health: Health,
    #[serde(rename = "initiative_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_revision: String,
    #[serde(rename = "membership_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub membership_revision: String,
    #[serde(rename = "name_snapshot")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name_snapshot: String,
    #[serde(rename = "observed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_at: Timestamp,
    #[serde(rename = "position")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub position: i64,
    #[serde(rename = "progress")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub progress: i64,
    #[serde(rename = "project_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub project_id: String,
    #[serde(rename = "snapshot_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub snapshot_revision: String,
    #[serde(rename = "status_category")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status_category: Status,
    #[serde(rename = "target_date")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_date: Option<String>,
    #[serde(rename = "target_start")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_start: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AttachProjectError {
    AlreadyAttached,
    Archived,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    NotAttached,
    NotFound,
    OperationInProgress,
    PositionConflict,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DetachProjectRequest {
    #[serde(rename = "expected_initiative_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_initiative_revision: String,
    #[serde(rename = "expected_membership_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_membership_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "initiative_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_id: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "project_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub project_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DetachProjectResponse {
    #[serde(rename = "detached")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub detached: bool,
    #[serde(rename = "initiative_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_revision: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DetachProjectError {
    AlreadyAttached,
    Archived,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    NotAttached,
    NotFound,
    OperationInProgress,
    PositionConflict,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReorderProjectsRequest {
    #[serde(rename = "expected_initiative_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_initiative_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "initiative_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_id: String,
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<ReorderProjectsRequestItemsItem>,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReorderProjectsRequestItemsItem {
    #[serde(rename = "expected_membership_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_membership_revision: String,
    #[serde(rename = "position")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub position: i64,
    #[serde(rename = "project_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub project_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReorderProjectsResponse {
    #[serde(rename = "initiative_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_revision: String,
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<ReorderProjectsResponseItemsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReorderProjectsResponseItemsItem {
    #[serde(rename = "membership_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub membership_revision: String,
    #[serde(rename = "position")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub position: i64,
    #[serde(rename = "project_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub project_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReorderProjectsError {
    AlreadyAttached,
    Archived,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    NotAttached,
    NotFound,
    OperationInProgress,
    PositionConflict,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UpdateProjectSnapshotRequest {
    #[serde(rename = "expected_membership_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_membership_revision: String,
    #[serde(rename = "health")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub health: Health,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "initiative_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_id: String,
    #[serde(rename = "name_snapshot")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name_snapshot: String,
    #[serde(rename = "observed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_at: Timestamp,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "progress")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub progress: i64,
    #[serde(rename = "project_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub project_id: String,
    #[serde(rename = "snapshot_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub snapshot_revision: String,
    #[serde(rename = "status_category")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status_category: Status,
    #[serde(rename = "target_date")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_date: Option<String>,
    #[serde(rename = "target_start")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_start: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UpdateProjectSnapshotResponse {
    #[serde(rename = "health")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub health: Health,
    #[serde(rename = "initiative_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub initiative_revision: String,
    #[serde(rename = "membership_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub membership_revision: String,
    #[serde(rename = "name_snapshot")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name_snapshot: String,
    #[serde(rename = "observed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub observed_at: Timestamp,
    #[serde(rename = "position")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub position: i64,
    #[serde(rename = "progress")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub progress: i64,
    #[serde(rename = "project_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub project_id: String,
    #[serde(rename = "snapshot_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub snapshot_revision: String,
    #[serde(rename = "status_category")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status_category: Status,
    #[serde(rename = "target_date")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_date: Option<String>,
    #[serde(rename = "target_start")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_start: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UpdateProjectSnapshotError {
    AlreadyAttached,
    Archived,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    NotAttached,
    NotFound,
    OperationInProgress,
    PositionConflict,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ProjectPortfolioAdminArchiveInitiative;
impl RequestCapability for ProjectPortfolioAdminArchiveInitiative {
    type Request = ArchiveInitiativeRequest;
    type Response = ArchiveInitiativeResponse;
    type DomainError = ArchiveInitiativeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ARCHIVE_INITIATIVE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ProjectPortfolioAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).archive_initiative(context, request)
    }
}

#[derive(Debug)]
pub struct ProjectPortfolioAdminAttachProject;
impl RequestCapability for ProjectPortfolioAdminAttachProject {
    type Request = AttachProjectRequest;
    type Response = AttachProjectResponse;
    type DomainError = AttachProjectError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ATTACH_PROJECT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ProjectPortfolioAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).attach_project(context, request)
    }
}

#[derive(Debug)]
pub struct ProjectPortfolioAdminDetachProject;
impl RequestCapability for ProjectPortfolioAdminDetachProject {
    type Request = DetachProjectRequest;
    type Response = DetachProjectResponse;
    type DomainError = DetachProjectError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DETACH_PROJECT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ProjectPortfolioAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).detach_project(context, request)
    }
}

#[derive(Debug)]
pub struct ProjectPortfolioAdminReorderProjects;
impl RequestCapability for ProjectPortfolioAdminReorderProjects {
    type Request = ReorderProjectsRequest;
    type Response = ReorderProjectsResponse;
    type DomainError = ReorderProjectsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REORDER_PROJECTS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ProjectPortfolioAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).reorder_projects(context, request)
    }
}

#[derive(Debug)]
pub struct ProjectPortfolioAdminUpdateProjectSnapshot;
impl RequestCapability for ProjectPortfolioAdminUpdateProjectSnapshot {
    type Request = UpdateProjectSnapshotRequest;
    type Response = UpdateProjectSnapshotResponse;
    type DomainError = UpdateProjectSnapshotError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != UPDATE_PROJECT_SNAPSHOT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ProjectPortfolioAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).update_project_snapshot(context, request)
    }
}

impl serde::Serialize for ArchiveInitiativeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyAttached => serializer.serialize_str("already_attached"),
            Self::Archived => serializer.serialize_str("archived"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotAttached => serializer.serialize_str("not_attached"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::PositionConflict => serializer.serialize_str("position_conflict"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ArchiveInitiativeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_attached" => Ok(Self::AlreadyAttached),
                "archived" => Ok(Self::Archived),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_attached" => Ok(Self::NotAttached),
                "not_found" => Ok(Self::NotFound),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "position_conflict" => Ok(Self::PositionConflict),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for AttachProjectError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyAttached => serializer.serialize_str("already_attached"),
            Self::Archived => serializer.serialize_str("archived"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotAttached => serializer.serialize_str("not_attached"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::PositionConflict => serializer.serialize_str("position_conflict"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AttachProjectError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_attached" => Ok(Self::AlreadyAttached),
                "archived" => Ok(Self::Archived),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_attached" => Ok(Self::NotAttached),
                "not_found" => Ok(Self::NotFound),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "position_conflict" => Ok(Self::PositionConflict),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for DetachProjectError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyAttached => serializer.serialize_str("already_attached"),
            Self::Archived => serializer.serialize_str("archived"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotAttached => serializer.serialize_str("not_attached"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::PositionConflict => serializer.serialize_str("position_conflict"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DetachProjectError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_attached" => Ok(Self::AlreadyAttached),
                "archived" => Ok(Self::Archived),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_attached" => Ok(Self::NotAttached),
                "not_found" => Ok(Self::NotFound),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "position_conflict" => Ok(Self::PositionConflict),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReorderProjectsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyAttached => serializer.serialize_str("already_attached"),
            Self::Archived => serializer.serialize_str("archived"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotAttached => serializer.serialize_str("not_attached"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::PositionConflict => serializer.serialize_str("position_conflict"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReorderProjectsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_attached" => Ok(Self::AlreadyAttached),
                "archived" => Ok(Self::Archived),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_attached" => Ok(Self::NotAttached),
                "not_found" => Ok(Self::NotFound),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "position_conflict" => Ok(Self::PositionConflict),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for UpdateProjectSnapshotError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyAttached => serializer.serialize_str("already_attached"),
            Self::Archived => serializer.serialize_str("archived"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotAttached => serializer.serialize_str("not_attached"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::PositionConflict => serializer.serialize_str("position_conflict"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for UpdateProjectSnapshotError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_attached" => Ok(Self::AlreadyAttached),
                "archived" => Ok(Self::Archived),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_attached" => Ok(Self::NotAttached),
                "not_found" => Ok(Self::NotFound),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "position_conflict" => Ok(Self::PositionConflict),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_archive_initiative_request(value: &ArchiveInitiativeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_archive_initiative_request(wire: &str) -> Result<ArchiveInitiativeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_archive_initiative_response(value: &ArchiveInitiativeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_archive_initiative_response(wire: &str) -> Result<ArchiveInitiativeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_archive_initiative_error(value: &ArchiveInitiativeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_archive_initiative_error(wire: &str) -> Result<ArchiveInitiativeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_attach_project_request(value: &AttachProjectRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_attach_project_request(wire: &str) -> Result<AttachProjectRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_attach_project_response(value: &AttachProjectResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_attach_project_response(wire: &str) -> Result<AttachProjectResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_attach_project_error(value: &AttachProjectError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_attach_project_error(wire: &str) -> Result<AttachProjectError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_detach_project_request(value: &DetachProjectRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_detach_project_request(wire: &str) -> Result<DetachProjectRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_detach_project_response(value: &DetachProjectResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_detach_project_response(wire: &str) -> Result<DetachProjectResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_detach_project_error(value: &DetachProjectError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_detach_project_error(wire: &str) -> Result<DetachProjectError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_reorder_projects_request(value: &ReorderProjectsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_reorder_projects_request(wire: &str) -> Result<ReorderProjectsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_reorder_projects_response(value: &ReorderProjectsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_reorder_projects_response(wire: &str) -> Result<ReorderProjectsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_reorder_projects_error(value: &ReorderProjectsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_reorder_projects_error(wire: &str) -> Result<ReorderProjectsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_update_project_snapshot_request(value: &UpdateProjectSnapshotRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_project_snapshot_request(wire: &str) -> Result<UpdateProjectSnapshotRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_update_project_snapshot_response(value: &UpdateProjectSnapshotResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_project_snapshot_response(wire: &str) -> Result<UpdateProjectSnapshotResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_update_project_snapshot_error(value: &UpdateProjectSnapshotError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_project_snapshot_error(wire: &str) -> Result<UpdateProjectSnapshotError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoProjectPortfolioAdminArchiveInitiativeResult {
    fn __lenso_into_result(self) -> Result<Result<ArchiveInitiativeResponse, ArchiveInitiativeError>, RuntimeFailure>;
}
impl __LensoIntoProjectPortfolioAdminArchiveInitiativeResult for Result<ArchiveInitiativeResponse, ArchiveInitiativeError> {
    fn __lenso_into_result(self) -> Result<Result<ArchiveInitiativeResponse, ArchiveInitiativeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoProjectPortfolioAdminArchiveInitiativeResult for Result<Result<ArchiveInitiativeResponse, ArchiveInitiativeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ArchiveInitiativeResponse, ArchiveInitiativeError>, RuntimeFailure> { self }
}
impl __LensoIntoProjectPortfolioAdminArchiveInitiativeResult for Result<ArchiveInitiativeResponse, lenso_plugin_authoring::PluginError<ArchiveInitiativeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ArchiveInitiativeResponse, ArchiveInitiativeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoProjectPortfolioAdminArchiveInitiativeResult for Result<ArchiveInitiativeResponse, ProjectPortfolioAdminArchiveInitiativeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ArchiveInitiativeResponse, ArchiveInitiativeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ProjectPortfolioAdminArchiveInitiativeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ProjectPortfolioAdminArchiveInitiativeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoProjectPortfolioAdminAttachProjectResult {
    fn __lenso_into_result(self) -> Result<Result<AttachProjectResponse, AttachProjectError>, RuntimeFailure>;
}
impl __LensoIntoProjectPortfolioAdminAttachProjectResult for Result<AttachProjectResponse, AttachProjectError> {
    fn __lenso_into_result(self) -> Result<Result<AttachProjectResponse, AttachProjectError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoProjectPortfolioAdminAttachProjectResult for Result<Result<AttachProjectResponse, AttachProjectError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AttachProjectResponse, AttachProjectError>, RuntimeFailure> { self }
}
impl __LensoIntoProjectPortfolioAdminAttachProjectResult for Result<AttachProjectResponse, lenso_plugin_authoring::PluginError<AttachProjectError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AttachProjectResponse, AttachProjectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoProjectPortfolioAdminAttachProjectResult for Result<AttachProjectResponse, ProjectPortfolioAdminAttachProjectInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AttachProjectResponse, AttachProjectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ProjectPortfolioAdminAttachProjectInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ProjectPortfolioAdminAttachProjectInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoProjectPortfolioAdminDetachProjectResult {
    fn __lenso_into_result(self) -> Result<Result<DetachProjectResponse, DetachProjectError>, RuntimeFailure>;
}
impl __LensoIntoProjectPortfolioAdminDetachProjectResult for Result<DetachProjectResponse, DetachProjectError> {
    fn __lenso_into_result(self) -> Result<Result<DetachProjectResponse, DetachProjectError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoProjectPortfolioAdminDetachProjectResult for Result<Result<DetachProjectResponse, DetachProjectError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DetachProjectResponse, DetachProjectError>, RuntimeFailure> { self }
}
impl __LensoIntoProjectPortfolioAdminDetachProjectResult for Result<DetachProjectResponse, lenso_plugin_authoring::PluginError<DetachProjectError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DetachProjectResponse, DetachProjectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoProjectPortfolioAdminDetachProjectResult for Result<DetachProjectResponse, ProjectPortfolioAdminDetachProjectInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DetachProjectResponse, DetachProjectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ProjectPortfolioAdminDetachProjectInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ProjectPortfolioAdminDetachProjectInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoProjectPortfolioAdminReorderProjectsResult {
    fn __lenso_into_result(self) -> Result<Result<ReorderProjectsResponse, ReorderProjectsError>, RuntimeFailure>;
}
impl __LensoIntoProjectPortfolioAdminReorderProjectsResult for Result<ReorderProjectsResponse, ReorderProjectsError> {
    fn __lenso_into_result(self) -> Result<Result<ReorderProjectsResponse, ReorderProjectsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoProjectPortfolioAdminReorderProjectsResult for Result<Result<ReorderProjectsResponse, ReorderProjectsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReorderProjectsResponse, ReorderProjectsError>, RuntimeFailure> { self }
}
impl __LensoIntoProjectPortfolioAdminReorderProjectsResult for Result<ReorderProjectsResponse, lenso_plugin_authoring::PluginError<ReorderProjectsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReorderProjectsResponse, ReorderProjectsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoProjectPortfolioAdminReorderProjectsResult for Result<ReorderProjectsResponse, ProjectPortfolioAdminReorderProjectsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReorderProjectsResponse, ReorderProjectsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ProjectPortfolioAdminReorderProjectsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ProjectPortfolioAdminReorderProjectsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoProjectPortfolioAdminUpdateProjectSnapshotResult {
    fn __lenso_into_result(self) -> Result<Result<UpdateProjectSnapshotResponse, UpdateProjectSnapshotError>, RuntimeFailure>;
}
impl __LensoIntoProjectPortfolioAdminUpdateProjectSnapshotResult for Result<UpdateProjectSnapshotResponse, UpdateProjectSnapshotError> {
    fn __lenso_into_result(self) -> Result<Result<UpdateProjectSnapshotResponse, UpdateProjectSnapshotError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoProjectPortfolioAdminUpdateProjectSnapshotResult for Result<Result<UpdateProjectSnapshotResponse, UpdateProjectSnapshotError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<UpdateProjectSnapshotResponse, UpdateProjectSnapshotError>, RuntimeFailure> { self }
}
impl __LensoIntoProjectPortfolioAdminUpdateProjectSnapshotResult for Result<UpdateProjectSnapshotResponse, lenso_plugin_authoring::PluginError<UpdateProjectSnapshotError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<UpdateProjectSnapshotResponse, UpdateProjectSnapshotError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoProjectPortfolioAdminUpdateProjectSnapshotResult for Result<UpdateProjectSnapshotResponse, ProjectPortfolioAdminUpdateProjectSnapshotInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<UpdateProjectSnapshotResponse, UpdateProjectSnapshotError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ProjectPortfolioAdminUpdateProjectSnapshotInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ProjectPortfolioAdminUpdateProjectSnapshotInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ProjectPortfolioAdminProvider: fmt::Debug + 'static {
    fn archive_initiative(&self, context: InvocationContext, request: ArchiveInitiativeRequest) -> NativeRequestFuture<ProjectPortfolioAdminArchiveInitiative>;
    fn attach_project(&self, context: InvocationContext, request: AttachProjectRequest) -> NativeRequestFuture<ProjectPortfolioAdminAttachProject>;
    fn detach_project(&self, context: InvocationContext, request: DetachProjectRequest) -> NativeRequestFuture<ProjectPortfolioAdminDetachProject>;
    fn reorder_projects(&self, context: InvocationContext, request: ReorderProjectsRequest) -> NativeRequestFuture<ProjectPortfolioAdminReorderProjects>;
    fn update_project_snapshot(&self, context: InvocationContext, request: UpdateProjectSnapshotRequest) -> NativeRequestFuture<ProjectPortfolioAdminUpdateProjectSnapshot>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_project_portfolio_admin {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportProjectPortfolioAdmin;
        impl $crate::ProjectPortfolioAdminProvider for $plugin {
        fn archive_initiative(&self, context: __LensoNativeSupportProjectPortfolioAdmin::InvocationContext, request: $crate::ArchiveInitiativeRequest) -> __LensoNativeSupportProjectPortfolioAdmin::NativeRequestFuture<$crate::ProjectPortfolioAdminArchiveInitiative> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::archive_initiative(&plugin, context, request).await;
                $crate::__LensoIntoProjectPortfolioAdminArchiveInitiativeResult::__lenso_into_result(result)
            })
        }
        fn attach_project(&self, context: __LensoNativeSupportProjectPortfolioAdmin::InvocationContext, request: $crate::AttachProjectRequest) -> __LensoNativeSupportProjectPortfolioAdmin::NativeRequestFuture<$crate::ProjectPortfolioAdminAttachProject> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::attach_project(&plugin, context, request).await;
                $crate::__LensoIntoProjectPortfolioAdminAttachProjectResult::__lenso_into_result(result)
            })
        }
        fn detach_project(&self, context: __LensoNativeSupportProjectPortfolioAdmin::InvocationContext, request: $crate::DetachProjectRequest) -> __LensoNativeSupportProjectPortfolioAdmin::NativeRequestFuture<$crate::ProjectPortfolioAdminDetachProject> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::detach_project(&plugin, context, request).await;
                $crate::__LensoIntoProjectPortfolioAdminDetachProjectResult::__lenso_into_result(result)
            })
        }
        fn reorder_projects(&self, context: __LensoNativeSupportProjectPortfolioAdmin::InvocationContext, request: $crate::ReorderProjectsRequest) -> __LensoNativeSupportProjectPortfolioAdmin::NativeRequestFuture<$crate::ProjectPortfolioAdminReorderProjects> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::reorder_projects(&plugin, context, request).await;
                $crate::__LensoIntoProjectPortfolioAdminReorderProjectsResult::__lenso_into_result(result)
            })
        }
        fn update_project_snapshot(&self, context: __LensoNativeSupportProjectPortfolioAdmin::InvocationContext, request: $crate::UpdateProjectSnapshotRequest) -> __LensoNativeSupportProjectPortfolioAdmin::NativeRequestFuture<$crate::ProjectPortfolioAdminUpdateProjectSnapshot> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::update_project_snapshot(&plugin, context, request).await;
                $crate::__LensoIntoProjectPortfolioAdminUpdateProjectSnapshotResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct ProjectPortfolioAdminRequestEndpoint { provider: Rc<dyn ProjectPortfolioAdminProvider> }

#[derive(Debug)]
pub struct ProjectPortfolioAdminEndpoint<P: ProjectPortfolioAdminProvider> { provider: Rc<P>, request_endpoint: ProjectPortfolioAdminRequestEndpoint }
impl<P: ProjectPortfolioAdminProvider> ProjectPortfolioAdminEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ProjectPortfolioAdminProvider> = provider.clone();
        Self { provider, request_endpoint: ProjectPortfolioAdminRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ProjectPortfolioAdminProvider> NativeRequestEndpoint for ProjectPortfolioAdminEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ARCHIVE_INITIATIVE_OPERATION,
        ATTACH_PROJECT_OPERATION,
        DETACH_PROJECT_OPERATION,
        REORDER_PROJECTS_OPERATION,
        UPDATE_PROJECT_SNAPSHOT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ARCHIVE_INITIATIVE_OPERATION => {
                let Ok(request) = request.downcast::<ArchiveInitiativeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).archive_initiative(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            ATTACH_PROJECT_OPERATION => {
                let Ok(request) = request.downcast::<AttachProjectRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).attach_project(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            DETACH_PROJECT_OPERATION => {
                let Ok(request) = request.downcast::<DetachProjectRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).detach_project(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REORDER_PROJECTS_OPERATION => {
                let Ok(request) = request.downcast::<ReorderProjectsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).reorder_projects(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            UPDATE_PROJECT_SNAPSHOT_OPERATION => {
                let Ok(request) = request.downcast::<UpdateProjectSnapshotRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).update_project_snapshot(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_project_portfolio_admin {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ProjectPortfolioAdminEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_project_portfolio_admin {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_project_portfolio_admin!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ProjectPortfolioAdminClient {
    archive_initiative: NativeRequestHandle<ProjectPortfolioAdminArchiveInitiative>,
    attach_project: NativeRequestHandle<ProjectPortfolioAdminAttachProject>,
    detach_project: NativeRequestHandle<ProjectPortfolioAdminDetachProject>,
    reorder_projects: NativeRequestHandle<ProjectPortfolioAdminReorderProjects>,
    update_project_snapshot: NativeRequestHandle<ProjectPortfolioAdminUpdateProjectSnapshot>,
}
impl ProjectPortfolioAdminClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn archive_initiative(&self, request: ArchiveInitiativeRequest) -> Result<ArchiveInitiativeResponse, ProjectPortfolioAdminArchiveInitiativeInvocationError> {
        self.archive_initiative.invoke(ARCHIVE_INITIATIVE_OPERATION, request).await
            .map_err(ProjectPortfolioAdminArchiveInitiativeInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminArchiveInitiativeInvocationError::Domain)
    }

    pub async fn archive_initiative_with_context(&self, context: InvocationContext, request: ArchiveInitiativeRequest) -> Result<ArchiveInitiativeResponse, ProjectPortfolioAdminArchiveInitiativeInvocationError> {
        self.archive_initiative.invoke_with_context(ARCHIVE_INITIATIVE_OPERATION, context, request).await
            .map_err(ProjectPortfolioAdminArchiveInitiativeInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminArchiveInitiativeInvocationError::Domain)
    }

    pub async fn attach_project(&self, request: AttachProjectRequest) -> Result<AttachProjectResponse, ProjectPortfolioAdminAttachProjectInvocationError> {
        self.attach_project.invoke(ATTACH_PROJECT_OPERATION, request).await
            .map_err(ProjectPortfolioAdminAttachProjectInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminAttachProjectInvocationError::Domain)
    }

    pub async fn attach_project_with_context(&self, context: InvocationContext, request: AttachProjectRequest) -> Result<AttachProjectResponse, ProjectPortfolioAdminAttachProjectInvocationError> {
        self.attach_project.invoke_with_context(ATTACH_PROJECT_OPERATION, context, request).await
            .map_err(ProjectPortfolioAdminAttachProjectInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminAttachProjectInvocationError::Domain)
    }

    pub async fn detach_project(&self, request: DetachProjectRequest) -> Result<DetachProjectResponse, ProjectPortfolioAdminDetachProjectInvocationError> {
        self.detach_project.invoke(DETACH_PROJECT_OPERATION, request).await
            .map_err(ProjectPortfolioAdminDetachProjectInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminDetachProjectInvocationError::Domain)
    }

    pub async fn detach_project_with_context(&self, context: InvocationContext, request: DetachProjectRequest) -> Result<DetachProjectResponse, ProjectPortfolioAdminDetachProjectInvocationError> {
        self.detach_project.invoke_with_context(DETACH_PROJECT_OPERATION, context, request).await
            .map_err(ProjectPortfolioAdminDetachProjectInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminDetachProjectInvocationError::Domain)
    }

    pub async fn reorder_projects(&self, request: ReorderProjectsRequest) -> Result<ReorderProjectsResponse, ProjectPortfolioAdminReorderProjectsInvocationError> {
        self.reorder_projects.invoke(REORDER_PROJECTS_OPERATION, request).await
            .map_err(ProjectPortfolioAdminReorderProjectsInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminReorderProjectsInvocationError::Domain)
    }

    pub async fn reorder_projects_with_context(&self, context: InvocationContext, request: ReorderProjectsRequest) -> Result<ReorderProjectsResponse, ProjectPortfolioAdminReorderProjectsInvocationError> {
        self.reorder_projects.invoke_with_context(REORDER_PROJECTS_OPERATION, context, request).await
            .map_err(ProjectPortfolioAdminReorderProjectsInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminReorderProjectsInvocationError::Domain)
    }

    pub async fn update_project_snapshot(&self, request: UpdateProjectSnapshotRequest) -> Result<UpdateProjectSnapshotResponse, ProjectPortfolioAdminUpdateProjectSnapshotInvocationError> {
        self.update_project_snapshot.invoke(UPDATE_PROJECT_SNAPSHOT_OPERATION, request).await
            .map_err(ProjectPortfolioAdminUpdateProjectSnapshotInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminUpdateProjectSnapshotInvocationError::Domain)
    }

    pub async fn update_project_snapshot_with_context(&self, context: InvocationContext, request: UpdateProjectSnapshotRequest) -> Result<UpdateProjectSnapshotResponse, ProjectPortfolioAdminUpdateProjectSnapshotInvocationError> {
        self.update_project_snapshot.invoke_with_context(UPDATE_PROJECT_SNAPSHOT_OPERATION, context, request).await
            .map_err(ProjectPortfolioAdminUpdateProjectSnapshotInvocationError::Runtime)?
            .map_err(ProjectPortfolioAdminUpdateProjectSnapshotInvocationError::Domain)
    }
}

impl CapabilityClient for ProjectPortfolioAdminClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            archive_initiative: dependencies.one::<ProjectPortfolioAdminArchiveInitiative>()?,
            attach_project: dependencies.one::<ProjectPortfolioAdminAttachProject>()?,
            detach_project: dependencies.one::<ProjectPortfolioAdminDetachProject>()?,
            reorder_projects: dependencies.one::<ProjectPortfolioAdminReorderProjects>()?,
            update_project_snapshot: dependencies.one::<ProjectPortfolioAdminUpdateProjectSnapshot>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ProjectPortfolioAdminClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    archive_initiative: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ProjectPortfolioAdminArchiveInitiative>()?,
                    attach_project: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ProjectPortfolioAdminAttachProject>()?,
                    detach_project: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ProjectPortfolioAdminDetachProject>()?,
                    reorder_projects: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ProjectPortfolioAdminReorderProjects>()?,
                    update_project_snapshot: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ProjectPortfolioAdminUpdateProjectSnapshot>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectPortfolioAdminArchiveInitiativeInvocationError {
    Domain(ArchiveInitiativeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ProjectPortfolioAdminAttachProjectInvocationError {
    Domain(AttachProjectError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ProjectPortfolioAdminDetachProjectInvocationError {
    Domain(DetachProjectError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ProjectPortfolioAdminReorderProjectsInvocationError {
    Domain(ReorderProjectsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ProjectPortfolioAdminUpdateProjectSnapshotInvocationError {
    Domain(UpdateProjectSnapshotError),
    Runtime(RuntimeFailure),
}
